# Enable mouse scrolling
set -g mouse on

# Clean status bar (no session name or date/time)
set -g status-left ''
set -g status-right ''

# Seamless navigation between vim splits and tmux panes
set -g @plugin 'christoomey/vim-tmux-navigator'

# Select panes (with prefix, as fallback)
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

bind x kill-pane

bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key H resize-pane -L 10
bind-key L resize-pane -R 10

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Automatically set window name to git root directory
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#(cd #{pane_current_path}; $HOME/tmux-window-name.sh)'

set -g renumber-windows on

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'


