brew install neovim
brew install 1password
brew install arc
brew install cursor
brew install raycast
brew install ghostty
brew install granola
brew install cleanshot
brew install zoom
brew install contexts
brew install slack
brew install pure
brew install zsh-syntax-highlighting
brew install pnpm
brew install eza
brew install gh
brew install karabiner-elements
brew install descript
brew install zoom
brew install fnm
brew install fzf
brew install gh
brew install zoxide
brew install yt-dlp
brew install ripgrep
brew install --cask jordanbaird-ice
